# -*- mode: ruby -*-
#vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.define "control" do |control|
    control.vm.box = "bento/ubuntu-16.04"
    control.vm.hostname = "control"
    control.vm.network "private_network", ip: "192.168.33.20"
    control.vm.provision "shell", path: "install.sh", args: "control"
  end

  config.vm.define "compute01" do |compute01|
    compute01.vm.box = "bento/ubuntu-16.04"
    compute01.vm.hostname = "compute01"
    compute01.vm.network "private_network", ip: "192.168.33.21"
    compute01.vm.provision "shell", path: "install.sh", args: "compute01"
  end

  config.vm.define "compute02" do |compute02|
    compute02.vm.box = "bento/ubuntu-16.04"
    compute02.vm.hostname = "compute02"
    compute02.vm.network "private_network", ip: "192.168.33.22"
    compute02.vm.provision "shell", path: "install.sh", args: "compute02"
  end

  if Vagrant.has_plugin?("vagrant-cachier")
    config.cache.scope = :box
  end

  config.ssh.forward_agent = true

  config.vm.provider "virtualbox" do |vb|
     vb.customize ["modifyvm", :id, "--memory", "4096"]
     vb.customize ["modifyvm", :id, "--cpus", "2"]
  end

  #config.vm.provision :shell do |shell|
  #  shell.path = "install.sh"
  #end
end
